import { Node, Edge } from '@xyflow/react';

interface ExportOptions {
  format: 'turtle' | 'owl-xml' | 'json-ld';
  includeNamespaces: boolean;
  includeMetadata: boolean;
}

export class GraphExporter {
  private static getNamespaces(): Record<string, string> {
    return {
      rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
      rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
      owl: 'http://www.w3.org/2002/07/owl#',
      foaf: 'http://xmlns.com/foaf/0.1/',
      org: 'https://www.w3.org/TR/vocab-org/',
      dc: 'http://purl.org/dc/elements/1.1/',
      xsd: 'http://www.w3.org/2001/XMLSchema#'
    };
  }

  static exportToTurtle(nodes: Node[], edges: Edge[], options: ExportOptions = {
    format: 'turtle',
    includeNamespaces: true,
    includeMetadata: true
  }): string {
    const namespaces = this.getNamespaces();
    let turtle = '';

    // Add namespace prefixes
    if (options.includeNamespaces) {
      Object.entries(namespaces).forEach(([prefix, uri]) => {
        turtle += `@prefix ${prefix}: <${uri}> .\n`;
      });
      turtle += '\n';
    }

    // Add metadata
    if (options.includeMetadata) {
      turtle += `# Knowledge Graph exported on ${new Date().toISOString()}\n`;
      turtle += `# Generated by Ontology Painter\n\n`;
    }

    // Export individuals/nodes
    nodes.forEach(node => {
      const { classType, individualName, namespace, properties } = node.data;
      const individualUri = `${namespace}:${String(individualName).replace(/\s+/g, '_')}`;
      const classUri = `${namespace}:${classType}`;
      
      turtle += `${individualUri} a ${classUri} ;\n`;
      
      // Add properties
      Object.entries(properties || {}).forEach(([prop, value], index, array) => {
        const isLast = index === array.length - 1;
        turtle += `    ${prop} "${value}"`;
        turtle += isLast ? ' .\n\n' : ' ;\n';
      });
    });

    // Export relationships/edges
    edges.forEach(edge => {
      const sourceNode = nodes.find(n => n.id === edge.source);
      const targetNode = nodes.find(n => n.id === edge.target);
      
      if (sourceNode && targetNode && edge.data) {
        const sourceUri = `${sourceNode.data.namespace}:${String(sourceNode.data.individualName).replace(/\s+/g, '_')}`;
        const targetUri = `${targetNode.data.namespace}:${String(targetNode.data.individualName).replace(/\s+/g, '_')}`;
        const propertyUri = edge.data.propertyType;
        
        turtle += `${sourceUri} ${propertyUri} ${targetUri} .\n`;
      }
    });

    return turtle;
  }

  static exportToOwlXml(nodes: Node[], edges: Edge[], options: ExportOptions = {
    format: 'owl-xml',
    includeNamespaces: true,
    includeMetadata: true
  }): string {
    const namespaces = this.getNamespaces();
    
    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
    xml += '<rdf:RDF';
    
    // Add namespace declarations
    if (options.includeNamespaces) {
      Object.entries(namespaces).forEach(([prefix, uri]) => {
        xml += `\n    xmlns:${prefix}="${uri}"`;
      });
    }
    
    xml += '>\n\n';

    if (options.includeMetadata) {
      xml += `<!-- Knowledge Graph exported on ${new Date().toISOString()} -->\n`;
      xml += `<!-- Generated by Ontology Painter -->\n\n`;
    }

    // Export ontology header
    xml += '    <owl:Ontology rdf:about="">\n';
    xml += '        <rdfs:label>Exported Knowledge Graph</rdfs:label>\n';
    xml += `        <dc:created>${new Date().toISOString()}</dc:created>\n`;
    xml += '    </owl:Ontology>\n\n';

    // Export individuals
    nodes.forEach(node => {
      const { classType, individualName, namespace, properties } = node.data;
      const individualId = String(individualName).replace(/\s+/g, '_');
      
      xml += `    <${namespace}:${classType} rdf:about="#${individualId}">\n`;
      
      Object.entries(properties || {}).forEach(([prop, value]) => {
        xml += `        <${prop}>${value}</${prop}>\n`;
      });
      
      xml += `    </${namespace}:${classType}>\n\n`;
    });

    // Export object properties
    edges.forEach(edge => {
      const sourceNode = nodes.find(n => n.id === edge.source);
      const targetNode = nodes.find(n => n.id === edge.target);
      
      if (sourceNode && targetNode && edge.data) {
        const sourceId = String(sourceNode.data.individualName).replace(/\s+/g, '_');
        const targetId = String(targetNode.data.individualName).replace(/\s+/g, '_');
        const property = String(edge.data.propertyType).split(':');
        
        xml += `    <owl:ObjectPropertyAssertion>\n`;
        xml += `        <owl:ObjectProperty IRI="#${property[1]}" />\n`;
        xml += `        <owl:NamedIndividual IRI="#${sourceId}" />\n`;
        xml += `        <owl:NamedIndividual IRI="#${targetId}" />\n`;
        xml += `    </owl:ObjectPropertyAssertion>\n\n`;
      }
    });

    xml += '</rdf:RDF>';
    return xml;
  }

  static exportToJsonLd(nodes: Node[], edges: Edge[], options: ExportOptions = {
    format: 'json-ld',
    includeNamespaces: true,
    includeMetadata: true
  }): string {
    const namespaces = this.getNamespaces();
    
    const jsonLd: any = {
      '@context': options.includeNamespaces ? namespaces : {},
      '@graph': []
    };

    if (options.includeMetadata) {
      jsonLd['@graph'].push({
        '@type': 'owl:Ontology',
        'rdfs:label': 'Exported Knowledge Graph',
        'dc:created': new Date().toISOString(),
        'dc:creator': 'Ontology Painter'
      });
    }

    // Export individuals
    nodes.forEach(node => {
      const { classType, individualName, namespace, properties } = node.data;
      const individual: any = {
        '@id': `${namespace}:${String(individualName).replace(/\s+/g, '_')}`,
        '@type': `${namespace}:${classType}`
      };

      Object.entries(properties || {}).forEach(([prop, value]) => {
        individual[prop] = value;
      });

      jsonLd['@graph'].push(individual);
    });

    // Export relationships
    edges.forEach(edge => {
      const sourceNode = nodes.find(n => n.id === edge.source);
      const targetNode = nodes.find(n => n.id === edge.target);
      
      if (sourceNode && targetNode && edge.data) {
        const sourceId = `${sourceNode.data.namespace}:${String(sourceNode.data.individualName).replace(/\s+/g, '_')}`;
        const targetId = `${targetNode.data.namespace}:${String(targetNode.data.individualName).replace(/\s+/g, '_')}`;
        
        // Find the source individual in the graph and add the relationship
        const sourceIndividual = jsonLd['@graph'].find((item: any) => item['@id'] === sourceId);
        if (sourceIndividual && edge.data.propertyType) {
          sourceIndividual[String(edge.data.propertyType)] = { '@id': targetId };
        }
      }
    });

    return JSON.stringify(jsonLd, null, 2);
  }

  static downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  static exportGraph(nodes: Node[], edges: Edge[], format: 'turtle' | 'owl-xml' | 'json-ld'): void {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    
    let content: string;
    let filename: string;
    let mimeType: string;

    switch (format) {
      case 'turtle':
        content = this.exportToTurtle(nodes, edges);
        filename = `knowledge-graph-${timestamp}.ttl`;
        mimeType = 'text/turtle';
        break;
      case 'owl-xml':
        content = this.exportToOwlXml(nodes, edges);
        filename = `knowledge-graph-${timestamp}.owl`;
        mimeType = 'application/rdf+xml';
        break;
      case 'json-ld':
        content = this.exportToJsonLd(nodes, edges);
        filename = `knowledge-graph-${timestamp}.jsonld`;
        mimeType = 'application/ld+json';
        break;
      default:
        throw new Error(`Unsupported format: ${format}`);
    }

    this.downloadFile(content, filename, mimeType);
  }
}